# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 504e421d85b2c68e639f06a373b0d0d754cb134abc04b81219d21f62db927e7503627481b2153e71ee4551b53579d3772e6419b39e66253399dfcf919a7e54ea

test:
  secret_key_base: e66806110a9028f394f8f9f831e549973a9b42f18b807ebcada3e7bec4ee7b111f00bb572d5387b834b9454e5d44b41258520f23572e2b500a0222f29532ff4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
